---
- name: set tuned profile
  action: command tuned-adm profile latency-performance
    
<<<<<<< HEAD
# Here we use a state changed as an indicator of a new install
- name: Install the release CLC packages
  action: yum name=eucalyptus-cloud state=latest enablerepo=eucalyptus-release,euca2ools-release,elrepo,epel,base,updates
  when: not nightlies

- name: Install the nightly CLC packages
  action: yum name=eucalyptus-cloud state=latest enablerepo=eucalyptus-nightly,euca2ools-release,elrepo,epel,base,updates
  when: nightlies
=======
    # Here we use a state changed as an indicator of a new install
    - name: Install the release CLC packages
      action: yum name=eucalyptus-cloud state=latest enablerepo=eucalyptus-release,euca2ools-release,elrepo,epel,base,updates
      when: not nightlies

    - name: Install the nightly CLC packages
      action: yum name=eucalyptus-cloud state=latest enablerepo=eucalyptus-nightly,euca2ools-release,elrepo,epel,base,updates
      when: nightlies
>>>>>>> 97a741e2bd5ff4ccdf8e1a2a5bf8056f0ce5b937

- name: Template the configuration file
  action: template src=../../common/templates/eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf

<<<<<<< HEAD
# Only initialize the database if packages were installed
# (its a new environment)
- name: Initialize the database
  action: command /usr/sbin/euca_conf --initialize creates=/var/lib/eucalyptus/keys/euca.p12  
  register: init
=======
    # Only initialize the database if packages were installed
    # (its a new environment)
    - name: Initialize the database
      action: command /usr/sbin/euca_conf --initialize creates=/var/lib/eucalyptus/keys/euca.p12  
      notify: restart eucalyptus cloud
>>>>>>> 97a741e2bd5ff4ccdf8e1a2a5bf8056f0ce5b937

- name: Restart CLC 
  service: name=eucalyptus-cloud state=restarted
  when: init.changed

# Wait for services to come up 
- name: Waiting for CLC services
  action: wait_for port=8777 delay=15

# Before we register commands, we need to copy move keys around.
- name: Fetch cloud keys
  action: fetch src=/var/lib/eucalyptus/keys/{{ item }} dest=/tmp/ flat=yes
  with_items:
  - cloud-cert.pem
  - cloud-pk.pem
  - euca.p12
